custom_stopwords_eng = [
    "a", "an", "the", "and", "or", "but", "for", "with", "in", "on", "at", "to", "from", "of", "by", "as", "is", "are",
    "were", "was", "be", "been", "being", "have", "has", "had", "do", "does", "did", "will", "would", "can", "could",
    "should", "must", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "/", ",", ".", ":", ";", "(", ")",
    "[", "]", "{", "}", "'", "\"", "‘", "’", "“", "”", "he", "she", "it", "they", "we", "you", "that", "which", "who",
    "whom", "whose", "of", "to", "in", "for", "on", "with", "by", "at", "from", "into", "onto", "upon", "among",
    "between", "within", "without", "under", "over", "through", "during", "before", "after", "since", "about",
    "around", "against", "beside", "beyond", "above", "below", "throughout", "toward", "across", "is", "am", "are",
    "was", "were", "be", "being", "been", "have", "has", "had", "do", "does", "did", "will", "would", "shall", "should",
    "may", "might", "can", "could", "must", "good", "bad", "well", "better", "best", "often", "sometimes", "always",
    "never", "many", "few", "much", "little", "more", "less", "most", "least", "thou", "thee", "thine", "thy", "ye",
    "hath", "hast", "art", "didst", "doth", "wast", "were", "whence", "whom", "wilt"
]

greek_punctuation = [
    ",", ".", ";", ":", "·", "·", "—", "!", "?", "(", ")", "[", "]", "{", "}", "«", "»", "'", "’", "ʼ", "‘", "“", "”",
    "‹", "›", "„", "«", "»", "‹", "›", "„", "‹", "›", "»", "«"
]
"""
Greek: 'Kyle P. Johnson <kyle@kyle-p-johnson.com>', from the Perseus Hopper source [http://sourceforge.net/projects/perseus-hopper], found at "/sgml/reading/build/stoplists", though this only contained acute accents on the ultima. There has been added to this grave accents to the ultima of each. Perseus source is made available under the Mozilla Public License 1.1 (MPL 1.1) [http://www.mozilla.org/MPL/1.1/].
"""

greek_stopwords = [
    "αὐτὸς",
    "αὐτός",
    "γε",
    "γὰρ",
    "γάρ",
    "δ'",
    "δαὶ",
    "δαὶς",
    "δαί",
    "δαίς",
    "διὰ",
    "διά",
    "δὲ",
    "δέ",
    "δὴ",
    "δή",
    "εἰ",
    "εἰμὶ",
    "εἰμί",
    "εἰς",
    "εἴμι",
    "κατὰ",
    "κατά",
    "καὶ",
    "καί",
    "μετὰ",
    "μετά",
    "μὲν",
    "μέν",
    "μὴ",
    "μή",
    "οἱ",
    "οὐ",
    "οὐδεὶς",
    "οὐδείς",
    "οὐδὲ",
    "οὐδέ",
    "οὐκ",
    "οὔτε",
    "οὕτως",
    "οὖν",
    "οὗτος",
    "παρὰ",
    "παρά",
    "περὶ",
    "περί",
    "πρὸς",
    "πρός",
    "σὸς",
    "σός",
    "σὺ",
    "σὺν",
    "σύ",
    "σύν",
    "τε",
    "τι",
    "τις",
    "τοιοῦτος",
    "τοὶ",
    "τοί",
    "τοὺς",
    "τούς",
    "τοῦ",
    "τὰ",
    "τά",
    "τὴν",
    "τήν",
    "τὶ",
    "τὶς",
    "τί",
    "τίς",
    "τὸ",
    "τὸν",
    "τό",
    "τόν",
    "τῆς",
    "τῇ",
    "τῶν",
    "τῷ",
    "ἀλλ'",
    "ἀλλὰ",
    "ἀλλά",
    "ἀπὸ",
    "ἀπό",
    "ἂν",
    "ἄλλος",
    "ἄν",
    "ἄρα",
    "ἐγὼ",
    "ἐγώ",
    "ἐκ",
    "ἐξ",
    "ἐμὸς",
    "ἐμός",
    "ἐν",
    "ἐπὶ",
    "ἐπί",
    "ἐὰν",
    "ἐάν",
    "ἑαυτοῦ",
    "ἔτι",
    "ἡ",
    "ἢ",
    "ἤ",
    "ὁ",
    "ὃδε",
    "ὃς",
    "ὅδε",
    "ὅς",
    "ὅστις",
    "ὅτι",
    "ὑμὸς",
    "ὑμός",
    "ὑπὲρ",
    "ὑπέρ",
    "ὑπὸ",
    "ὑπό",
    "ὡς",
    "ὥστε",
    "ὦ",
    "ξύν",
    "ξὺν",
    "σύν",
    "σὺν",
    "τοῖς",
    "τᾶς",
]

custom_stopwords_grk = greek_stopwords + greek_punctuation
